export const clientsData = [
    {
        email: 'nik@nik.nik',
        domain:  'nikisthebest.nik',
        transactionId: 1,
        amount: 3.50,
        currency: 'USD',
        openedDate: new Date(new Date() - 3600000).toISOString(),
        completedDate: new Date().toISOString(),
        status: ['Bill', 'Canceled', 'Completed', 'In-progress'][0],
        key: 0,
    },
    {
        email: 'nik1@nik.nik',
        domain:  'nik1isthebest.nik',
        transactionId: 2,
        amount: 31.50,
        currency: 'NIS',
        openedDate: new Date(new Date() - 7200000).toISOString(),
        completedDate: new Date().toISOString(),
        status: ['Bill', 'Canceled', 'Completed', 'In-progress'][1],
        key: 1,
    },
    {
        email: 'nik2@nik.nik',
        domain:  'nik2isthebest.nik',
        transactionId: 3,
        amount: 4.50,
        currency: 'USD',
        openedDate: new Date(new Date() - 3600000).toISOString(),
        completedDate: new Date().toISOString(),
        status: ['Bill', 'Canceled', 'Completed', 'In-progress'][2],
        key: 2,
    },
    {
        email: 'nik3@nik.nik',
        domain:  'nik3isthebest.nik',
        transactionId: 4,
        amount: 2.50,
        currency: 'USD',
        openedDate: new Date(new Date() - 10800000).toISOString(),
        completedDate: new Date().toISOString(),
        status: ['Bill', 'Canceled', 'Completed', 'In-progress'][3],
        key: 3,
    },
    {
        email: 'nik4@nik.nik',
        domain:  'nik4isthebest.nik',
        transactionId: 5,
        amount: 9,
        currency: 'USD',
        openedDate: new Date(new Date() - 3600000).toISOString(),
        completedDate: new Date().toISOString(),
        status: ['Bill', 'Canceled', 'Completed', 'In-progress'][2],
        key: 4,
    },
    {
        email: 'nik5@nik.nik',
        domain:  'nik5isthebest.nik',
        transactionId: 6,
        amount: 10,
        currency: 'EUR',
        openedDate: new Date(new Date() - 3600000).toISOString(),
        completedDate: new Date().toISOString(),
        status: ['Bill', 'Canceled', 'Completed', 'In-progress'][3],
        key: 5,
    },
    {
        email: 'nik6@nik.nik',
        domain:  'nik6isthebest.nik',
        transactionId: 7,
        amount: 88,
        currency: 'RUB',
        openedDate: new Date(new Date() - 3600000).toISOString(),
        completedDate: new Date().toISOString(),
        status: ['Bill', 'Canceled', 'Completed', 'In-progress'][1],
        key: 6,
    },

]